### ISSUE TITLE
Question: learning new site structure?

### ISSUE THREAD

**Issue by matysek145** [scrapinghub/portia#134]
Hi, firstly i must say that this is very nice tool, i was thinking about making something similar and then i found this eventually - seems really great :)

But i've got a question.

I presume that Portia uses templates to learn what and how to scrap and it uses some machine learning techniques and templates act like training sets.

But what will happen, if site structure changes in time?

My idea was to use already fetched data to find out new structure and this way create new templates - all automatically, probably even without notifying the user.

I didn't find anything about this in description or another issues, but maybe i just missed something.

Could you explain me what will happen if site structure changes? Do i have to provide new templates or is Portia capable of learn new structure by itself? :)

I hope I explained my problem well

Cheers.

**Comment by ruairif** [comment]
I'm happy you like. You're absolutely right with your assumptions as to how Portia works. Unfortunately if a site structure changes you need to build new templates so that Portia can continue to extract the correct data.

Currently we have no way of doing what you want but we have discussed adding it. From these discussions we have put together a proposal for this years Google Summer of Code to build a system that can re-learn how to extract data from a site.

If you are eligible to apply or know somebody who would enjoy this challenge please get in contact with us.

I've added a link to the proposal below.
https://github.com/scrapinghub/portia/wiki/GSoC-2015-Ideas#id7
