### ISSUE TITLE
Installation instructions not in right order

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#427]
In this installation instruction https://portia.readthedocs.org/en/latest/installation.html#running-portia-locally

```
Install the following dependencies:

sudo ./provision.sh install_deps
```

comes before

```
Now clone this repository into that env:

git clone https://github.com/scrapinghub/portia.git
```

problem: `provision.sh` is not available before repository is cloned

**Comment by the4ndy** [comment]
I also noticed that even if you clone first and then proceed that the second ./provision.sh command fails because one of the PPA urls is invalid

`W: Failed to fetch http://ppa.launchpad.net/pi-rho/security/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found`

jessie is not a valid ubuntu dist, its the name of a debian dist if im not mistaken

**Comment by rootinshell** [comment]
`http://ppa.launchpad.net/pi-rho/security/ubuntu/dists/jessie/main/binary-amd64/Packages` no longer exist
