### ISSUE TITLE
Using ember-data in slyd/app?

### ISSUE THREAD

**Issue by netpaladinx** [scrapinghub/portia#567]
I saw the _slyd_ frontend JavaScript application is based on _ember.js_. But when I read the source code in _slyd/app_, I didn't find _ember-data_ models which should be defined by _DS.Model.extend()_. Is this a important feature of ember.js? Why didn't the slyd frontend use this feature? Does this design have other considerations?

**Comment by ruairif** [comment]
At the time Portia was initially developed Ember Data wasn't stable. This has since changed though so we have changed portia to use Ember Data and the latest Ember. This development has been ongoing in the `nui-develop` and `nui-master` branches. If you want to use the upcoming Portia release you can try it out in one of those 2 branches.
